### ISSUE TITLE
libpng fails on OS64 with missing NEON detection option

### ISSUE THREAD

**Issue by AJenbo** [leetal/ios-cmake#118]
This might be related to erroneous feature detection

**Comment by leetal** [comment]
Hi! Did you solve this? I saw that the PR mentioned in the other issue had it's version of libPNG upped and I just wonder if that was due to issued in the libPNG buildchain or with this toolchain?

**Comment by AJenbo** [comment]
we ended up forcing it with a flag

**Comment by leetal** [comment]
Ah okay. So was there an actual issue with this toolchain or libPNG itself? I have actually managed to build libPNG a couple of years ago for iOS and back then, libPNG lacked support for the correct runtime checks of NEON on iOS. Only Android & Linux had implemented runtime checks. Back then, if i recall correctly, specifying `-DPNG_ARM_NEON=on` was sufficient (since all ARM SoCs since at least armv6 has support for NEON out of the box).

**Comment by AJenbo** [comment]
Yeah that is the solution we ended up with as well, I wonder if there is a way to detect this automatically?
