### ISSUE TITLE
[JFYI] CMake 3.14

### ISSUE THREAD

**Issue by ddovod** [leetal/ios-cmake#27]
Hi guys. I've just found some info about "official" iOS support in cmake
https://cmake.org/cmake/help/v3.14/release/3.14.html#platforms
and corresponding cmake files in the `cmake_repo/Modules/Platform`.

It would be great to adopt and simplify this toolchain file to be used with cmake 3.14

**Comment by leetal** [comment]
I will look into this and perhaps add conditionals since lots of the functionality provided requires you to generate Xcode projects which is more or less not how this toolchain was first designed. So fixing this would require some conditional steps to be added that checks if generating makefiles(or other build intermediaries) or an Xcode project (via -G xcode flag)

**Comment by leetal** [comment]
Fixed in [v3.0.0](https://github.com/leetal/ios-cmake/tree/3.0.0) 🔥 🌶
