### ISSUE TITLE
example-app build error

### ISSUE THREAD

**Issue by Y-JunKang** [leetal/ios-cmake#57]
I entered the following command at the terminal：
 
```sh
cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../../ios.toolchain.cmake -DPLATFORM=OS
cmake --build . --config Release --target install
```
Get a libexample.a . and the architecture for libexample:
```sh
➜  example-lib $ lipo -info lib/libexample.a 
Architectures in the fat file: lib/libexample.a are: armv7 armv7s arm64 
```

But i get a error when i run example-app with Xcode (target iPhone8 device not simulator).

```
ld: warning: ignoring file /Users/Tomy/Downloads/ios-cmake-master 2/example/example-app/example-lib/lib/libexample.dylib, file was built for i386 which is not the architecture being linked (arm64): /Users/Tomy/Downloads/ios-cmake-master 2/example/example-app/example-lib/lib/libexample.dylib
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_HelloWorldIOS", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
CMake version: 3.14.5

How can i fix it.

**Comment by leetal** [comment]
This error is caused by the example-lib project not installing itself into the example app directory upon install. If you would copy the example-lib artifact into the example-app folder (under .../example-app/example-lib, I know this is confusing as hell...) it would work. This is due to the example-app project is only there to showcase the file structure. I will modify the example-lib install target to actually install the file into the example-app directory to limit the confusion levels.
