### ISSUE TITLE
Contribute to CMake's first-class iOS, tvOS, and watchOS support

### ISSUE THREAD

**Issue by agirault** [leetal/ios-cmake#58]
Was looking at your toolchain which was really helpful, but I did hit some issues with recent CMake versions. After more digging, I found out that CMake 3.14 has first-class support for iOS etc:

- doc: https://cmake.org/cmake/help/v3.14/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos
- pr: https://gitlab.kitware.com/cmake/cmake/merge_requests/2392

It leverages the [`CMAKE_SYSTEM_NAME`](https://cmake.org/cmake/help/v3.14/variable/CMAKE_SYSTEM_NAME.html) variable which is consistent with doing cross-platform in general on CMake, which is quite nice.

It might be interesting to try to consolidate your work with what @gjasny contributed in CMake?

Best

**Comment by leetal** [comment]
This toolchains main purpose is to be CMake-version agnostic and thus have support for the combined builds support for iOS, watchOS and tvOS (starting from 3.14.4 due to bugs in earlier versions) included. Following the steps provided by me [here](https://github.com/leetal/ios-cmake/issues/55#issuecomment-520803665) shall yield a combined, static build for iOS with x86_64 and arm64 slices included. We use this every day in our production build systems om multiple projects without any issues with combined builds. Did this answer this issue's topic?

**Comment by agirault** [comment]
My issue topic was more about encouraging upstreaming your work to CMake to make it first-class support in the future, given that CMake now has early support for iOS/watchOS/tvOS natively, which will be maintained in the future versions of CMake. Further development in CMake will also probably keep leading to compatibility issues with the toolchain from this repo, and consolidating your work back to CMake would help to avoid that.

Just a suggestion. Thanks for your work which has been very helpful.
