### ISSUE TITLE
SDL Build fails

### ISSUE THREAD

**Issue by hsdk123** [leetal/ios-cmake#75]
**Describe the bug**
Hi, I'm trying to build SDL for iOS using the repo here: https://github.com/SDL-mirror/SDL
CMake configuration goes fine, but builds fail with the error:

```
SDL_rwops.c:386:9: error: implicit declaration of function 'fseeko64' is invalid in C99

if (fseek(context->hidden.stdio.fp, (fseek_off_t)offset, stdiowhence) == 0 {

SDL_rwops.c:313:17: note: expanded from macro 'fseek'
#define fseek fseeko64
```
(complains also about ftell, off64_t, etc.

**To Reproduce**
```
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=../../ios-cmake/ios.toolchain.cmake \
    -DPLATFORM=OS64 \
    -DCMAKE_INSTALL_PREFIX=~/ios-libs
cmake --build .
```

**Expected behavior**
Build.

**Environment**
* What version of CMake did you run? OSX 10.15.6

**Comment by leetal** [comment]
This is probably an issue with LFS on Darwin. It has nothing to do with this toolchain. It probably has something to do with missing compile time definition to CMake or the like. I recommend you to look through the sdl CMakeLists.txt and look for references like Apple, Darwin, macos or ios and see if any of the options will make it compile on Darwin platforms.

See here for potential workarounds or further troubleshooting: https://stackoverflow.com/questions/4003479/how-to-enable-large-file-support-under-darwin

Closing this since this issue per say have nothing to do with the toolchain. Ask on StackOverflow if the above link does not help you out.
