### ISSUE TITLE
Is it possible to build universal iOS library?

### ISSUE THREAD

**Issue by zhouhao27** [leetal/ios-cmake#8]
Is it possible to build universal iOS library so that we don't need to specify the platform?

**Comment by leetal** [comment]
Not at the moment. I've thought about adding a CMake build-step that builds a universal library (eg. with lipo on static libs). But came to the conclusion that such behaviour would not be intuitive. The toolchain is just a "helping hand" and should by design only help with the core issue; - Building single binaries based on users needs, without having to worry about setting the correct CPPFLAGS to the compiler. But this said, nothing stops you from adding such a buildstep to your CMakeLists file yourself. :)

**Comment by zhouhao27** [comment]
Thanks @leetal.
