### ISSUE TITLE
Need an option to build OS64 libraries without code signing

### ISSUE THREAD

**Issue by gwang-msft** [leetal/ios-cmake#86]
**Describe the bug**
If you are trying to build OS64 or any platform which is not a simulator, you will be forced to code sign the output. When building from a Mac without code signing certificate (no Apple developer account), the CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM will be set as "123456789A" and the build will fail with error message,

Code Signing Error: No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "123456789A" with a private key was found.

**To Reproduce**
1. Build any project for device (not simulator) such as OS64 without providing CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM 

**Expected behavior**
Be able build without code signing.
Not every libraries are required to be code signed, for example,
- Static linked libraries do not require code signing
- App developers may choose to code sign the dynamic library manually late
- For CIs verifying building, adding code signing will be extra work without obvious benefits

**Environment**
* What version of CMake did you run?
* Your faulty CMakeLists.txt here:
```cmake
--- Paste here ---
```
**Proposal**
Add an extra option to disable code signing, if CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM is not set.
Can send PR

**Comment by a4z** [comment]
is it even possible to build a binary without code signing? 
static libraries, but for binaries(apps) dynamic libraries and framework, I think its Apple that requires a signature
so I think it is not a cmake issue that signing fails .... or am I wrong? 
( I think you can build a dynamic library without signing, but you will not be able to load it, https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html)

**Comment by kkk669** [comment]
@a4z At least in case of XCFramework that consists of dynamic frameworks and is used via SwiftPM, it doesn't need code signing when you build it. When you build an app that depends on that XCFramework, it is automatically signed in one of building phases.

So, I agree with @gwang-msft.

**Comment by leetal** [comment]
I'll add this as soon as possible (most probably next week), unless someone can provide a PR sooner?

**Comment by a4z** [comment]
Please test the suggested fix, @kkk669 and @gwang-msft 
I have positive results on my machine.

**Comment by j3g** [comment]
I tried this fix. I just get a different error. I understand that I am selecting "Xcode" as my generator...should I do something different for static libraries. Thanks!
```
Check dependencies
Code Signing Error: Signing for "argonishche_sh" requires a development team. Select a development team in the Signing & Capabilities editor.

** BUILD FAILED **
```

I am trying to compile an open source library argon2. I will be linking it with other C code and eventually will be calling the code from iOS. I've done this before on Android but no experience on iOS. Here is the simple CMakeLists.txt file I'm testing on:
```cmake
cmake_minimum_required(VERSION 3.1)
  
project(external-argon2)
include(ExternalProject)

list(APPEND CMAKE_ARGS
    "-DCMAKE_TOOLCHAIN_FILE:PATH=${CMAKE_TOOLCHAIN_FILE}"
)

if(IOS)
    list(APPEND CMAKE_ARGS
        "-DPLATFORM=${PLATFORM}"
    )
endif()

ExternalProject_add(
    argon2
    URL https://github.com/yandex/argon2/archive/master.zip
    PREFIX argon2
    CMAKE_ARGS "${CMAKE_ARGS}"
    )

```

I execute the following cmake command taken from your examples
`cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=/Volumes/D1/dev/proj/.../cmake-ios/ios.toolchain.cmake -DPLATFORM=OS64`

**Comment by a4z** [comment]
you can always build with clang, and then there is no signature involved.
static libraries should not need any, even if you use xcode

I build frameworks, and for that this change works, 
but it could be for frameworks that this will be ignored anyway, since maybe XCode knows the consumer has to sign it )
because if you want a dynamic library for iOS you need a framework anyway, or are dynlib files supported ?

**Comment by a4z** [comment]
dynlibs outside of a framework are not supported, so signature feature is just relevant for frameworks

https://developer.apple.com/library/archive/technotes/tn2435/_index.html
See: Embedded .dylib Files
> The following errors may indicate your app is embedding a dynamic library that is not packaged as a framework. **Dynamic libraries outside of a framework bundle, which typically have the file extension .dylib, are not supported on iOS, watchOS, or tvOS**, except for the system Swift libraries provided by Xcode

So I think my PR is fine, the default value is disturbing and unwanted, since it must be possible to not add a signature for frameworks. And the default value of `123456789A` triggers an error, and should not be set.
And this is what  PR #94  fixes.
What @j3g is reporting, a signature problem with a static library, is obscure and must have a different reason.

@leetal , could you please consider adding the change from #94 ? 

And may I ask when you think you will prepare a release? I created a package for conan a while back, https://conan.io/center/ios-cmake , but I need already a M1 builds.
And having a release with this feature would avoid an intermediated release containing patches and going though one additional release review process to get the M1 and other fixes in.
But I would need how long the next release lies a head, approximately, to not make a patch version 1 day before a release and to know it's worth to wait.
